### ISSUE TITLE
你好，请问这个sdk的调用有没有次数限制？

### ISSUE THREAD

**Issue by zhengb0** [ikfly/java-tts#2]

**Comment by ikfly** [comment]
我并没有限制调用次数，现在能用的是edge浏览器语音朗读的端点，可能会有一些调用频率和长文限制，但我也不太清楚具体，抱歉

**Comment by qidai77777** [comment]
> 

我使用的时候，发现前两次发现正常生成了音频   但是过了一段时间之后就不行了
