### ISSUE TITLE
请问一下如何设置文件名称

### ISSUE THREAD

**Issue by BNUZ-YOscar** [ikfly/java-tts#3]
场景需要将生成的文件上传至云服务器，但是无法定位到底是哪个文件，发现文件名是根据内容生成的，如果文字内容太多岂不是文件名也很长了吗？

**Comment by ikfly** [comment]
文件名命名规则如下，前五个字加个时间戳，需要自定义命名自己扩展一下；
```
String fileName = (currentText.length() < 6 ? currentText : currentText.substring(0, 5)).replaceAll("[</|*。?\" >\\\\]","") + Tools.localDateTime();

```

**Comment by BNUZ-YOscar** [comment]
请问一下您是使用的google的tts api实现的吗?还是直接基于底层的tts；因为如果是谷歌的话，我看官方文档还需要配置认证信息，主要是怕万一哪天您的项目不维护了，我这边就无法调用了
&nbsp;


Tale
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月30日(星期一) 下午3:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ikfly/java-tts] 请问一下如何设置文件名称 (Issue #3)





 
文件名命名规则如下，前五个字加个时间戳，需要自定义命名自己扩展一下；
 String fileName = (currentText.length() < 6 ? currentText : currentText.substring(0, 5)).replaceAll("[</|*。?\" &gt;\\\\]","") + Tools.localDateTime();

**Comment by ikfly** [comment]
这个项目当前使用的是Edge浏览器语音朗读的逆向的api，当然我也是参考别人的项目改写的，你如果需要自己维护可以参考项目首页的感谢链接，有问题我也可以提供建议

**Comment by zglong** [comment]
java.net.ProtocolException: Expected HTTP 101 response but was '200 OK'
获取文件失败

**Comment by ikfly** [comment]
> java.net.ProtocolException: Expected HTTP 101 response but was '200 OK' 获取文件失败

usingAzureApi(true)   不要设置，azure 端点关了，刚刚更新了一下，把azure相关配置全删了，并更新了自定义输出文件名
