### ISSUE TITLE
咨询下使用

### ISSUE THREAD

**Issue by container-auto-tune** [ikfly/java-tts#4]
大佬你这个使用的是免费的额度吗？我这边试了下你的用起来很nice， 可能会大量使用，不知道能否使用

**Comment by ikfly** [comment]
这个使用的 egde 浏览器内置的语音朗读功能api，理论是没限制的

**Comment by container-auto-tune** [comment]
嗯嗯好的，感谢

**Comment by AE86-888** [comment]
在Linux系统上安装edge浏览器，是不是也就可以使用了
